name: Generate Animations

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install puppeteer @puppeteer/renderer
          npm install p5

      - name: Generate SVG Animations
        run: |
          mkdir -p output
          node .github/scripts/generate-svg.js

      - name: Push Generated SVGs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout --orphan output
          git reset
          mv output/* .
          git add *.svg
          git commit -m "Generate animations"
          git push origin output --force
